### ISSUE TITLE
Usability roadmap

### ISSUE THREAD

**Issue by emorice** [emorice/galp#57]
Tracker for the things that are frustrating when using galp on real projects
 * [x] Cannot pass a single item of a collection to task, you have to pass the whole collection, the index, and subscript inside the step -> done in https://github.com/emorice/galp/commit/3065535096864fa06bb998c8ec1151f1b6f0081c
 * ~~[ ] When developing, you need to change vtags often, and leave them in the final commit.~~
 * [ ] You can't move or rename a step
 * [x] Cannot inject a value several times in different contexts -> done in https://github.com/emorice/galp/commit/5b3742b634944090ee65e072c30141ab71db65bb
 * [ ] There should be a way to resolve short names
 * [ ] The helper `prepare_task` should work with shortened task names
 * [x] Big objects, either literals or graphs of tasks, should not crash jupyter when printing...
 * [ ] When debugging, the calls to prepare tasks or execute queries become long and repetitive really fast
