### ISSUE TITLE
Meta: memory management and other stories

### ISSUE THREAD

**Issue by emorice** [emorice/galp#8]
Status: divided in sub-issues
 * [x] #10 
 * [x] #26
 * [ ] to open: submission limits based on memory
 * [ ] to open: retrying tasks
 * [x] #25
 * [ ] to open: multithreading
 * [ ] #28 

Put your belts on, this one is going to be a long meta-issue.

It stems for our first attempt to run a real sized memory-bound pipeline on galp with limited success. In short, across several attempts, many or even all workers eventually crashed, presumably from OOM, leaving the pipeline uncompleted.

Of course this should be addressed primarily in the pipeline itself, by improving tasks to require less memory in the first place. However, I think it should be addressed in galp too. Having a step die of OOM is not a one-time thing. Optimizing memory is a time consuming task that can conflict with execution speed and the amount needed will change from one input to an other. So when developing new pipelines, one will run more than a few times into memory issues before getting it right, and galp must be here to help as much as possible.

Put broadly, galp should manage to run in a single invocation, all the tasks but the ones that require more that the total memory available to galp in a single step ; and these should be reported as such. So you can start an un-optimized pipeline on Friday, and clock in on Monday to find the list of tasks that took really, really too much memory and the results of all the others.

Now, to the smaller issues that need to get addressed to get there.

## Worker restart

See #10.

## Reporting killed-failed tasks

See #26.

## Limiting the submissions

Probably the largest issue. In short, we want to hold back on submit's that are likely to result in ooms until more tasks have finished. 

This requires to add to submits some resource requirements. This is a change in the GALP protocol. Probably, we want to add an  other array of key-value pairs to the submit message. This needs to be added in the message because the requirements will evolve along retries, for instance we may process several times the same submit with increasing memory allocations if a task keeps getting oom'ed.

Then, we need to filter tasks. At the simplest we can make them go through resource allocation points in order. This, however, will stop the whole queue if one task is waiting, but that's a start.

As usual an other issue would be to make sure resources are freed. However, with the nanny mechanism we should be relatively robust and be notified if a worker died, thus allowing us to consider whatever resources it was using freed. This  requires freed resources to be added to completion/failed notification, since we may not want the broker to keep a state for that. On the other hand nannies will keep state of corresponding worker's resources.

In brief: submits contains resource allocation. We allocate them when forwarding. Completion notices list resource freed.

An other question may be if we want the broker to take up this role. An argument in favor is that it's already what the broker's role is: queuing jobs until CPUs becomes available, each `READY` is essentially a CPU resource unit.

Also, we want to make sure we fail task asking for more than the total resources and not stupidly wait for more.

## Retrying failed tasks

Easy if all the rest is here. Upon receiving a failed with a error message suggesting an under-allocation, submits are requeud by the client or broker with a larger allocation.

## Keep the minimum in memory

See #25.

## Enable multithreading

For now we use one thread per worker, and distribute tasks among several workers. Having multithreaded workers running several tasks would work with our steps (MT over numpy with threadpoolctl to 1 works as intended for instance) and would allow massive memory saving in our test workflow. This would require to split the galp roles more cleanly, and we would need the improved resource cache handling described in the previous point. The task distribution logic is already implemented in the broker. We could implement chainable brokers (require a protocol change), or simply have each worker thread talk to the broker (much simpler I think). The shorter route is probably to use the workers as they are now, but start several of them in one process. The only thing to implement then would be to upgrade the cache system to support it being used from several threads at the same time ; for now it is asyncio-based which would need to change. Note than MT does not comes for free ; some steps would not run well in MT context if they use non threadsafe libraries or libraries that are globally locked (including python-heavy steps, or libraries that do not release the GIL), and this would make the whole thing much less robust since any thread could crash the whole worker process and take all the other tasks with it. Also, in such a case, you would not even be able to tell which task actually crashed the worker !
